services:
  worker:
    image: example/worker:latest
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    environment:
      WORKER_QUEUE_URL: ${WORKER_QUEUE_URL}
    networks:
      homelab_internal:
        ipv4_address: ${WORKER_NETWORK_IPV4}
