services:
  app:
    image: example/app:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      APP_SECRET: ${APP_SECRET}
      APP_RETENTION_HOURS: ${APP_RETENTION_HOURS:-168}
    volumes:
      - ${APP_DATA_DIR_MOUNT:-./${APP_DATA_DIR:-data/app-core}}:/var/lib/app
      - ${PWD:-.}/backups:/var/backups
    networks:
      homelab_internal:
        ipv4_address: ${APP_NETWORK_IPV4}
