# Compose base compartilhado. Combine com overrides de instância (ex.: core/media).
# Este arquivo define apenas recursos reutilizados pelas aplicações, como redes
# e volumes nomeados. Os serviços são declarados nos respectivos manifests em
# `compose/apps/<app>/`.

networks:
  homelab_internal:
    name: ${APP_NETWORK_NAME:-homelab_internal}
    driver: ${APP_NETWORK_DRIVER:-bridge}
    ipam:
      config:
        - subnet: ${APP_NETWORK_SUBNET}
          gateway: ${APP_NETWORK_GATEWAY}

volumes:
  homelab_shared_data:
    name: ${APP_SHARED_DATA_VOLUME_NAME:-homelab_shared_data}
