# Compose base compartilhado. Combine com overrides de instância (ex.: core/media).
# Define os defaults comuns para cada serviço "app"; os arquivos das aplicações
# apenas extendem/ajustam o que for necessário. O volume persistente aponta para
# `data/<app>-<instancia>`, resolvido automaticamente pelos scripts de deploy.

services:
  app:
    image: example/app:latest
    environment:
      TZ: ${TZ}
      APP_SECRET: ${APP_SECRET}
      APP_RETENTION_HOURS: ${APP_RETENTION_HOURS:-168}
    volumes:
      - ${APP_DATA_DIR_MOUNT}:/var/lib/app
      - ../backups:/var/backups
    restart: unless-stopped
