# Compose base compartilhado. Combine com overrides de instância (ex.: core/media).
services:
  app:
    image: example/app:latest
    environment:
      TZ: ${TZ}
      APP_SECRET: ${APP_SECRET}
      APP_RETENTION_HOURS: ${APP_RETENTION_HOURS:-168}
    volumes:
      - ../data/${SERVICE_NAME:-app}:/var/lib/app
      - ../backups:/var/backups
    restart: unless-stopped
