# Shared base Compose. Combine with instance overrides (e.g., core/media).
# This file only defines resources reused by applications, such as networks
# and named volumes. Services are declared directly in the respective
# `docker-compose.<instance>.yml` files.

networks:
  homelab_internal:
    name: ${APP_NETWORK_NAME:-homelab_internal}
    driver: ${APP_NETWORK_DRIVER:-bridge}
    ipam:
      config:
        - subnet: ${APP_NETWORK_SUBNET}
          gateway: ${APP_NETWORK_GATEWAY}

volumes:
  homelab_shared_data:
    name: ${APP_SHARED_DATA_VOLUME_NAME:-homelab_shared_data}
