name: Validate Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: find scripts -type f -name '*.sh' -print0 | xargs -0 -r shellcheck

      - name: Verify repository structure
        run: scripts/check_structure.sh

      - name: Validate compose configurations
        run: scripts/validate_compose.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run test suite
        run: python -m pytest
